version: '3'

services:
  django:
    build: ./api
    command: ["python", "backendapi/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
  frontend:
    build: 
      ./frontend
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]
    stdin_open: true
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
